# Generated by Django 3.2.13 on 2022-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedslotsbycoach',
            name='SESSION_DATE',
            field=models.CharField(blank=True, default='null', max_length=2000),
        ),
        migrations.AddField(
            model_name='confirmedslotsbycoach',
            name='SESSION_END_TIME',
            field=models.CharField(blank=True, default='null', max_length=2000),
        ),
        migrations.AddField(
            model_name='confirmedslotsbycoach',
            name='SESSION_START_TIME',
            field=models.CharField(blank=True, default='null', max_length=2000),
        ),
    ]
