# Generated by Django 3.2.13 on 2022-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='password',
        ),
        migrations.AddField(
            model_name='coach',
            name='meet_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='confirmedslotsbycoach',
            name='CC',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='confirmedslotsbycoach',
            name='MEETING_LINK',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='confirmedslotsbycoach',
            name='COACH_NAME',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='confirmedslotsbycoach',
            name='DESCRIPTION',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='confirmedslotsbycoach',
            name='SESSION_DATE',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='confirmedslotsbycoach',
            name='SESSION_END_TIME',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='confirmedslotsbycoach',
            name='SESSION_START_TIME',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='confirmedslotsbycoach',
            name='end_time',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='confirmedslotsbycoach',
            name='start_time',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='daytimeslot',
            name='day',
            field=models.CharField(choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thirsday', 'thirsday'), ('friday', 'friday'), ('saturday', 'saturday')], default='sunday', max_length=200),
        ),
        migrations.AlterField(
            model_name='daytimeslot',
            name='start_time_id',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slotforcoach',
            name='end_time',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='slotforcoach',
            name='start_time',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
    ]
