# Generated by Django 3.2.13 on 2022-09-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220908_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedslotsbycoach',
            name='DESCRIPTION',
            field=models.CharField(blank=True, default='null', max_length=2000),
        ),
    ]
