# Generated by Django 3.2.13 on 2022-08-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220822_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
        migrations.CreateModel(
            name='CoachCoachySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoomID', models.CharField(default='null', max_length=200)),
                ('isConfirmedByCoach', models.BooleanField(default=False)),
                ('isConfirmedByLearner', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.batch')),
                ('learner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.learners')),
                ('slot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.daytimeslot')),
            ],
        ),
    ]
