# Generated by Django 3.2.13 on 2022-08-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220817_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOneStartEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(blank=True, default='2000-01-01')),
                ('end_day', models.DateField(blank=True, default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='SessionTwoStartEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(blank=True, default='2000-01-01')),
                ('end_day', models.DateField(blank=True, default='2000-01-01')),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='start_day',
        ),
        migrations.AddField(
            model_name='sessions',
            name='coachingSessionOne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sessiononestartend'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='coachingSessionTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sessiontwostartend'),
        ),
    ]
