# Generated by Django 3.2.13 on 2022-07-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220706_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnerName', models.CharField(max_length=200)),
                ('learnerEmail', models.CharField(max_length=100)),
                ('learnerPhoneNumber', models.IntegerField()),
                ('learnerCompany', models.CharField(max_length=100)),
                ('learnerIndustry', models.CharField(max_length=100)),
                ('learnerDesignation', models.CharField(max_length=100)),
                ('learnerDOB', models.CharField(max_length=100)),
                ('learnerGender', models.CharField(max_length=100)),
                ('learnerCourse', models.CharField(max_length=100)),
                ('learnerBatch', models.CharField(max_length=100)),
            ],
        ),
    ]
