# Generated by Django 3.2.13 on 2022-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220909_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='coach',
            name='middle_name',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
