# Generated by Django 3.2.13 on 2022-09-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220901_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slotforcoach',
            name='expire_date',
            field=models.DateField(default='2022-09-10'),
        ),
    ]
