# Generated by Django 3.2.13 on 2022-08-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220804_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='fee',
            field=models.IntegerField(blank=True, default='6000'),
        ),
    ]
