# Generated by Django 3.2.13 on 2022-09-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220905_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotforcoach',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='expire_date',
            field=models.DateField(default='2022-09-10'),
        ),
    ]
