# Generated by Django 3.2.13 on 2022-07-07 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_learners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchStartDate', models.CharField(max_length=200)),
                ('batchName', models.CharField(max_length=200)),
                ('batchFaculty', models.CharField(max_length=200)),
                ('batchFees', models.CharField(max_length=200)),
                ('batchFrequency', models.CharField(max_length=200)),
                ('batchNoOfSessions', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.batch'),
        ),
    ]
