# Generated by Django 3.2.13 on 2022-09-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220912_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coachcoachysession',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='coachcoachysession',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='coachcoachysession',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='daytimeslot',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learnerdaytimeslot',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='learnerdaytimeslot',
            name='course',
        ),
        migrations.RemoveField(
            model_name='learnerdaytimeslot',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='learnerdaytimeslot',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='learners',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='learners',
            name='course',
        ),
        migrations.RemoveField(
            model_name='learners',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='course',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='CoachCoachySession',
        ),
        migrations.DeleteModel(
            name='CourseCategorys',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='DayTimeSlot',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='LearnerdayTimeSlot',
        ),
        migrations.DeleteModel(
            name='Learners',
        ),
        migrations.DeleteModel(
            name='Sessions',
        ),
    ]
