# Generated by Django 3.2.13 on 2022-08-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220817_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='coachingSessionOne',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='coachingSessionTwo',
        ),
        migrations.AddField(
            model_name='sessions',
            name='end_day',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='sessionNumber',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='start_day',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.DeleteModel(
            name='SessionOneStartEnd',
        ),
        migrations.DeleteModel(
            name='SessionTwoStartEnd',
        ),
    ]
