# Generated by Django 3.2.13 on 2022-08-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_coach_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learners',
            name='Course',
        ),
        migrations.AddField(
            model_name='learners',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.courses'),
        ),
    ]
