# Generated by Django 3.2.13 on 2022-09-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_confirmedslotsbycoach_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedslotsbycoach',
            name='COACH_NAME',
            field=models.CharField(blank=True, default='null', max_length=2000),
        ),
    ]
