# Generated by Django 3.2.13 on 2022-09-14 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220914_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotforcoach',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotforcoach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
