# Generated by Django 3.2.13 on 2022-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220804_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daytimeslot',
            old_name='dayofmock',
            new_name='day',
        ),
        migrations.AddField(
            model_name='daytimeslot',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='daytimeslot',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daytimeslot',
            name='session_id',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='daytimeslot',
            name='week_id',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='daytimeslot',
            name='end_time_id',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='daytimeslot',
            name='start_time_id',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fee',
            field=models.IntegerField(blank=True, default='6000'),
        ),
        migrations.AlterField(
            model_name='learners',
            name='Company',
            field=models.CharField(blank=True, default='000', max_length=100),
        ),
        migrations.AlterField(
            model_name='learners',
            name='Designation',
            field=models.CharField(blank=True, default='000', max_length=100),
        ),
        migrations.AlterField(
            model_name='learners',
            name='Gender',
            field=models.CharField(blank=True, default='male', max_length=100),
        ),
        migrations.AlterField(
            model_name='learners',
            name='Industry',
            field=models.CharField(blank=True, default='000', max_length=100),
        ),
    ]
