# Generated by Django 3.2.13 on 2022-08-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220811_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerdaytimeslot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='learnerdaytimeslot',
            name='end_time_id',
        ),
        migrations.RemoveField(
            model_name='learnerdaytimeslot',
            name='start_time_id',
        ),
        migrations.AddField(
            model_name='learnerdaytimeslot',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coach'),
        ),
        migrations.AddField(
            model_name='learnerdaytimeslot',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.courses'),
        ),
        migrations.AddField(
            model_name='learnerdaytimeslot',
            name='day',
            field=models.CharField(default='sunday', max_length=200),
        ),
        migrations.AddField(
            model_name='learnerdaytimeslot',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='learnerdaytimeslot',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnerdaytimeslot',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.daytimeslot'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('coach', 'coach'), ('admin', 'admin'), ('learner', 'learner'), ('faculty', 'faculty')], default='coach', max_length=50),
        ),
    ]
