# Generated by Django 3.2.13 on 2022-08-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220816_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='a@gmail.com', max_length=200),
        ),
    ]
