# Generated by Django 3.2.13 on 2022-08-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_coach_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learners',
            old_name='Batch',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='Industry',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='PhoneNumber',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='daytimeslot',
            name='for_learners',
            field=models.BooleanField(default=False),
        ),
    ]
