# Generated by Django 3.2.13 on 2022-07-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220707_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coursecategorys'),
        ),
    ]
