# Generated by Django 3.2.13 on 2022-10-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_events_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteConfirmedSlotsbyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_person', models.CharField(default=' ', max_length=200)),
                ('reason', models.CharField(default=' ', max_length=200)),
                ('slot_id', models.CharField(default=' ', max_length=200)),
                ('admin_name', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='min_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
