# Generated by Django 3.2.13 on 2022-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('date', models.DateField(blank=True, default='2000-01-01')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batchFaculty',
            new_name='Faculty',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batchFees',
            new_name='Fees',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batchFrequency',
            new_name='Frequency',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batchName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batchNoOfSessions',
            new_name='NoOfSessions',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='courseCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='courseName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='learnerBatch',
            new_name='Batch',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='learnerCompany',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='learnerCourse',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='learnerDOB',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='learnerDesignation',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='learnerEmail',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='learnerGender',
            new_name='Industry',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='learnerName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batchStartDate',
        ),
        migrations.RemoveField(
            model_name='learners',
            name='learnerIndustry',
        ),
        migrations.RemoveField(
            model_name='learners',
            name='learnerPhoneNumber',
        ),
        migrations.AddField(
            model_name='batch',
            name='StartDate',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='learners',
            name='DOB',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='learners',
            name='PhoneNumber',
            field=models.CharField(default='7880647282', max_length=1000),
        ),
        migrations.AlterField(
            model_name='coach',
            name='activeSince',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='dob',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='activeSince',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dob',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(max_length=2000),
        ),
    ]
