# Generated by Django 3.2.13 on 2022-11-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_events_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch', models.CharField(default=' ', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=200)),
                ('last_name', models.CharField(blank=True, default=' ', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(default=' ', max_length=200)),
                ('phone', models.CharField(blank=True, default=' ', max_length=200)),
                ('unique_check', models.CharField(default='null', max_length=200)),
                ('course', models.CharField(blank=True, default=' ', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='batch',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='status',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('coach', 'coach'), ('admin', 'admin'), ('leader', 'leader'), ('faculty', 'faculty')], default='coach', max_length=50),
        ),
        migrations.CreateModel(
            name='SubCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('competency', models.ManyToManyField(to='base.Competency')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(default=' ', max_length=200)),
                ('option_one', models.CharField(blank=True, default='null', max_length=200)),
                ('option_two', models.CharField(blank=True, default='null', max_length=200)),
                ('option_three', models.CharField(blank=True, default='null', max_length=200)),
                ('option_four', models.CharField(blank=True, default='null', max_length=200)),
                ('correct', models.CharField(blank=True, default='null', max_length=200)),
                ('score_one', models.IntegerField(blank=True, default=1)),
                ('score_two', models.IntegerField(blank=True, default=1)),
                ('score_three', models.IntegerField(blank=True, default=1)),
                ('score_four', models.IntegerField(blank=True, default=1)),
                ('scale', models.IntegerField(blank=True, default=5)),
                ('type', models.CharField(blank=True, default=' ', max_length=200)),
                ('sub_competency', models.ManyToManyField(to='base.SubCompetency')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, default=' ', max_length=200)),
                ('last_name', models.CharField(default=' ', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, default='NA', max_length=200)),
                ('isActive', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('type', models.CharField(default=' ', max_length=200)),
                ('competency', models.ManyToManyField(to='base.Competency')),
                ('question', models.ManyToManyField(to='base.Question')),
                ('sub_competency', models.ManyToManyField(to='base.SubCompetency')),
            ],
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('type', models.CharField(default=' ', max_length=200)),
                ('_id', models.CharField(default=' ', max_length=200)),
                ('batch', models.CharField(blank=True, default='null', max_length=200)),
                ('company', models.CharField(blank=True, default='null', max_length=200)),
                ('leader', models.CharField(default='null', max_length=200)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('start_date', models.DateField(blank=True, default='2000-01-01')),
                ('end_date', models.DateField(blank=True, default='2000-01-01')),
                ('course_assesment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.courseassesment')),
            ],
        ),
    ]
