# Generated by Django 3.2.13 on 2022-10-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_events_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='status',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
    ]
