# Generated by Django 3.2.13 on 2022-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_leanerconfirmedslots_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch', models.CharField(default=' ', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=200)),
                ('last_name', models.CharField(blank=True, default=' ', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(default=' ', max_length=200)),
                ('phone', models.CharField(blank=True, default=' ', max_length=200)),
                ('unique_check', models.CharField(default='null', max_length=200)),
                ('course', models.CharField(blank=True, default=' ', max_length=200)),
            ],
        ),
    ]
