# Generated by Django 3.2.13 on 2022-11-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_assesment_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_one', models.CharField(blank=True, default='null', max_length=200)),
                ('selected_option_two', models.CharField(blank=True, default='null', max_length=200)),
                ('selected_option_three', models.CharField(blank=True, default='null', max_length=200)),
                ('selected_option_four', models.CharField(blank=True, default='null', max_length=200)),
                ('gmail', models.CharField(blank=True, default='NA', max_length=200)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.question')),
            ],
        ),
        migrations.AlterField(
            model_name='assesment',
            name='_id',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.CreateModel(
            name='SubmittedAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('email', models.CharField(default=' ', max_length=200)),
                ('score', models.CharField(default=' ', max_length=200)),
                ('assesment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assesment')),
                ('question', models.ManyToManyField(to='base.SubmitedQuestion')),
            ],
        ),
    ]
