# Generated by Django 3.2.13 on 2022-11-07 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20221105_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleByleaderforAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('email', models.CharField(default=' ', max_length=200)),
                ('leader', models.CharField(default=' ', max_length=200)),
                ('assesment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assesment')),
            ],
        ),
    ]
