# Generated by Django 3.2.13 on 2022-12-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_events_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='end_date',
            field=models.DateField(default='2022-12-01'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='start_date',
            field=models.DateField(default='2022-12-01'),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='batch_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.events'),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='organisation',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='phone_no',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='about',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='is_coach_joined',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='is_learner_joined',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='is_reschedule',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='deleteconfirmedslotsbyadmin',
            name='slot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.confirmedslotsbycoach'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('coach', 'coach'), ('admin', 'admin'), ('learner', 'learner'), ('finance', 'finance')], default='coach', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceApprovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=100)),
                ('fees', models.IntegerField(default='500')),
                ('total_no_of_sessions', models.IntegerField(default=0)),
                ('generated_date', models.DateField()),
                ('generate_for_month', models.CharField(blank=True, default=' ', max_length=200)),
                ('generate_for_year', models.CharField(blank=True, default=' ', max_length=200)),
                ('is_approved', models.CharField(blank=True, default='null', max_length=200)),
                ('invoice_no', models.CharField(blank=True, default=' ', max_length=200)),
                ('rejection_reason', models.CharField(blank=True, default=' ', max_length=200)),
                ('response_by_finance_date', models.DateField(blank=True, default='2022-09-09')),
                ('coach_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coach')),
            ],
        ),
    ]
