# Generated by Django 3.2.13 on 2023-01-31 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_events_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(default=0, max_length=100)),
                ('rate', models.IntegerField(default=0)),
                ('number_of_session', models.IntegerField()),
                ('number_of_session_consumed', models.IntegerField(blank=True, default=0)),
                ('number_of_session_approved', models.BigIntegerField(blank=True, default=0)),
                ('valid_till', models.DateField()),
                ('status', models.CharField(default='OPEN', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='end_date',
            field=models.DateField(default='2022-12-01'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='start_date',
            field=models.DateField(default='2022-12-01'),
        ),
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='batch_name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.events'),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='organisation',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='phone_no',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='rescheduled_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.leanerconfirmedslots'),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='about',
            field=models.CharField(blank=True, default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='is_coach_joined',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='is_learner_joined',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='is_reschedule',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='deleteconfirmedslotsbyadmin',
            name='slot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.confirmedslotsbycoach'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('coach', 'coach'), ('admin', 'admin'), ('learner', 'learner'), ('finance', 'finance')], default='coach', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=0, max_length=100)),
                ('number_of_session', models.IntegerField()),
                ('is_approved', models.BooleanField(blank=True, default=False)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.purchaseorder')),
                ('rejected', models.ManyToManyField(blank=True, related_name='rejected', to='base.Rejected')),
            ],
        ),
        migrations.CreateModel(
            name='CoachPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coach')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='coach_price',
            field=models.ManyToManyField(blank=True, to='base.CoachPrice'),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='service_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.serviceapproval'),
        ),
    ]
