# Generated by Django 4.2.3 on 2023-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_events_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200)),
                ('body', models.TextField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
