# Generated by Django 3.2.13 on 2022-10-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_events_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(default=' ', max_length=200)),
                ('option_one', models.CharField(default='null', max_length=200)),
                ('option_two', models.CharField(default='null', max_length=200)),
                ('option_three', models.CharField(default='null', max_length=200)),
                ('option_four', models.CharField(default='null', max_length=200)),
                ('correct', models.CharField(blank=True, default='null', max_length=200)),
                ('score_one', models.IntegerField(blank=True, default=1)),
                ('score_two', models.IntegerField(blank=True, default=1)),
                ('score_three', models.IntegerField(blank=True, default=1)),
                ('score_four', models.IntegerField(blank=True, default=1)),
                ('scale', models.IntegerField(blank=True, default=5)),
                ('type', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('questions', models.ManyToManyField(to='base.Question')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('type', models.CharField(default=' ', max_length=200)),
                ('competency', models.ManyToManyField(to='base.Competency')),
                ('questions', models.ManyToManyField(to='base.Question')),
            ],
        ),
        migrations.AddField(
            model_name='competency',
            name='sub_competency',
            field=models.ManyToManyField(to='base.SubCompetency'),
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('type', models.CharField(default=' ', max_length=200)),
                ('_id', models.CharField(default=' ', max_length=200)),
                ('batch', models.CharField(default=' ', max_length=200)),
                ('company', models.CharField(default='null', max_length=200)),
                ('leader', models.CharField(default='null', max_length=200)),
                ('course_assesment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.competency')),
            ],
        ),
    ]
