# Generated by Django 3.2.13 on 2023-01-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20221220_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApprovalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_sessions', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deleteconfirmedslotsbyadmin',
            name='rescheduled_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.leanerconfirmedslots'),
        ),
        migrations.AddField(
            model_name='serviceapprovaldata',
            name='batch',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceapprovaldata',
            name='po_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ServiceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=100)),
                ('po_id', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(blank=True, default=False)),
                ('generated_on', models.DateField(blank=True)),
                ('responded_on', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.batch')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coach')),
                ('entries', models.ManyToManyField(blank=True, to='base.ServiceApprovalEntry')),
            ],
        ),
        migrations.CreateModel(
            name='CoachPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coach')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='coach_price',
            field=models.ManyToManyField(blank=True, to='base.CoachPrice'),
        ),
    ]
