# Generated by Django 3.2.13 on 2023-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20230131_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapproval',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
