# Generated by Django 3.2.13 on 2022-07-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_daytimeslot_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerdayTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.CharField(default='nishant', max_length=200)),
                ('start_time_id', models.CharField(max_length=200)),
                ('end_time_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='isSlotBooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_id',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
