# Generated by Django 3.2.13 on 2023-09-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_emailtemplate_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sent_to_participants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
