# Generated by Django 3.2.13 on 2022-11-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_serviceapprovaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('coach', 'coach'), ('admin', 'admin'), ('learner', 'learner'), ('finance', 'finance')], default='coach', max_length=50),
        ),
    ]
