# Generated by Django 4.2.3 on 2023-08-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_emailtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='body',
            new_name='template_data',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject',
        ),
    ]
