# Generated by Django 3.2.13 on 2022-10-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20221027_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='sub_competency',
        ),
        migrations.RemoveField(
            model_name='courseassesment',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='subcompetency',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='sub_competency',
            field=models.ManyToManyField(to='base.SubCompetency'),
        ),
        migrations.AddField(
            model_name='subcompetency',
            name='competency',
            field=models.ManyToManyField(to='base.Competency'),
        ),
    ]
