# Generated by Django 3.2.13 on 2023-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_serviceapproval_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapproval',
            name='req_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceapproval',
            name='invoice_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
