# Generated by Django 3.2.13 on 2022-10-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20221031_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassesment',
            name='question',
            field=models.ManyToManyField(to='base.Question'),
        ),
        migrations.AddField(
            model_name='courseassesment',
            name='sub_competency',
            field=models.ManyToManyField(to='base.SubCompetency'),
        ),
    ]
