# Generated by Django 4.2.3 on 2023-08-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_body_emailtemplate_template_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
