# Generated by Django 3.2.13 on 2022-07-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220728_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekStart', models.CharField(default='Null', max_length=200)),
                ('weekEnd', models.CharField(default='Null', max_length=200)),
                ('dayOne', models.CharField(default='Null', max_length=200)),
                ('dayTwo', models.CharField(default='Null', max_length=200)),
                ('dayThree', models.CharField(default='Null', max_length=200)),
                ('dayFour', models.CharField(default='Null', max_length=200)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.courses')),
            ],
        ),
    ]
