# Generated by Django 3.2.13 on 2022-11-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='is_coach_joined',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='is_learner_joined',
            field=models.CharField(blank=True, default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceapprovaldata',
            name='is_approved',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceapprovaldata',
            name='ref_id',
            field=models.CharField(max_length=100),
        ),
    ]
