# Generated by Django 3.2.13 on 2023-02-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20230204_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='requested_status',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='status_update_request',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='StatusUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=200)),
                ('requested_status', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner_confirmed_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.leanerconfirmedslots')),
            ],
        ),
    ]
