# Generated by Django 3.2.13 on 2022-10-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20221031_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='course_assesment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.courseassesment'),
        ),
    ]
