# Generated by Django 3.2.13 on 2023-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_emailtemplate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduledfor', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
