# Generated by Django 3.2.13 on 2022-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20221128_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='end_date',
            field=models.DateField(default='2022-12-01'),
        ),
    ]
