# Generated by Django 3.2.13 on 2022-12-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_adminrequest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leanerconfirmedslots',
            name='about',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
