# Generated by Django 3.2.13 on 2022-08-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='coach',
            name='password',
            field=models.CharField(default='Nish@@nt111', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='Nish@@nt111', max_length=50),
        ),
        migrations.AddField(
            model_name='learners',
            name='password',
            field=models.CharField(default='Nish@@nt111', max_length=50),
        ),
    ]
