# Generated by Django 3.2.13 on 2022-11-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20221102_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='batch',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='company',
            field=models.CharField(blank=True, default='null', max_length=200),
        ),
    ]
