# Generated by Django 3.2.13 on 2022-08-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220802_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='type',
        ),
    ]
