# Generated by Django 3.2.13 on 2022-11-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20221102_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='assesment',
            name='end_date',
            field=models.DateField(default=' '),
        ),
        migrations.AddField(
            model_name='assesment',
            name='start_date',
            field=models.DateField(default=' '),
        ),
    ]
