# Generated by Django 3.2.13 on 2022-08-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_bio_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('coach', 'coach'), ('learner', 'learner'), ('faculty', 'faculty')], default='coach', max_length=50),
        ),
    ]
