# Generated by Django 3.2.13 on 2022-08-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerdaytimeslot',
            name='date',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.batch'),
        ),
    ]
